const state = {
  audio: null,
  chart: null,
  selectedIndex: -1,
  activeIndex: -1,
  barRows: [],
  stemPlayers: [],
  soloStem: null,
  masterVolume: 0.55,
  playbackRate: 1,
  metronomeEnabled: false,
  metronomeVolume: 0.45,
  audioPreview: null,
  audioPreviewBusy: false,
  tuningReferenceHz: 440,
  timelineZoom: 1,
  followTimeCursor: true,
  detailPaneWidth: 236,
  chartRenderer: "table",
  currentView: "home",
  editorPanel: "arrange",
  loadingCount: 0,
  recentSessions: [],
  jobs: []
};

const PITCH_NAMES = ["C", "C#", "D", "Eb", "E", "F", "F#", "G", "Ab", "A", "Bb", "B"];
const ENHARMONIC_TO_PITCH = {
  "DB": "C#",
  "D#": "Eb",
  "GB": "F#",
  "G#": "Ab",
  "A#": "Bb"
};
const WHITE_KEYS = ["C", "D", "E", "F", "G", "A", "B"];
const BLACK_KEYS = [
  { note: "C#", afterWhite: 0 },
  { note: "Eb", afterWhite: 1 },
  { note: "F#", afterWhite: 3 },
  { note: "Ab", afterWhite: 4 },
  { note: "Bb", afterWhite: 5 }
];
const PIANO_OCTAVES = [3, 4];

const elements = {
  leftPane: document.getElementById("leftPane"),
  leftPaneToggle: document.getElementById("leftPaneToggle"),
  homeView: document.getElementById("homeView"),
  homeBuildInfo: document.getElementById("homeBuildInfo"),
  helpView: document.getElementById("helpView"),
  helpBuildInfo: document.getElementById("helpBuildInfo"),
  appBuildInfo: document.getElementById("appBuildInfo"),
  editorView: document.getElementById("editorView"),
  navItems: [...document.querySelectorAll(".nav-item")],
  projectNavItems: [...document.querySelectorAll(".project-nav")],
  homeNewProjectBtn: document.getElementById("homeNewProjectBtn"),
  homeOpenSessionBtn: document.getElementById("homeOpenSessionBtn"),
  homeGoSongBtn: document.getElementById("homeGoSongBtn"),
  youtubeStartForm: document.getElementById("youtubeStartForm"),
  youtubeUrlInput: document.getElementById("youtubeUrlInput"),
  youtubeStartBtn: document.getElementById("youtubeStartBtn"),
  youtubeSourceHint: document.getElementById("youtubeSourceHint"),
  clearRecentBtn: document.getElementById("clearRecentBtn"),
  currentProjectCard: document.getElementById("currentProjectCard"),
  recentSessionsList: document.getElementById("recentSessionsList"),
  jobList: document.getElementById("jobList"),
  chooseBtn: document.getElementById("chooseBtn"),
  analyzeBtn: document.getElementById("analyzeBtn"),
  openSessionBtn: document.getElementById("openSessionBtn"),
  saveSessionBtn: document.getElementById("saveSessionBtn"),
  fileLabel: document.getElementById("fileLabel"),
  topbarCover: document.getElementById("topbarCover"),
  topbarTitle: document.getElementById("topbarTitle"),
  audioPlayer: document.getElementById("audioPlayer"),
  sourceInfoPanel: document.getElementById("sourceInfoPanel"),
  masterVolumeInput: document.getElementById("masterVolumeInput"),
  masterVolumeText: document.getElementById("masterVolumeText"),
  arrangementMasterVolumeInput: document.getElementById("arrangementMasterVolumeInput"),
  arrangementMasterVolumeText: document.getElementById("arrangementMasterVolumeText"),
  playbackRateInput: document.getElementById("playbackRateInput"),
  playbackRateText: document.getElementById("playbackRateText"),
  arrangementPlaybackRateInput: document.getElementById("arrangementPlaybackRateInput"),
  arrangementPlaybackRateText: document.getElementById("arrangementPlaybackRateText"),
  metronomeEnabledInput: document.getElementById("metronomeEnabledInput"),
  metronomeVolumeInput: document.getElementById("metronomeVolumeInput"),
  metronomeVolumeText: document.getElementById("metronomeVolumeText"),
  activeBarText: document.getElementById("activeBarText"),
  statusText: document.getElementById("statusText"),
  titleInput: document.getElementById("titleInput"),
  keyInput: document.getElementById("keyInput"),
  keyNativeBtn: document.getElementById("keyNativeBtn"),
  keyOffsetText: document.getElementById("keyOffsetText"),
  arrangementKeyInput: document.getElementById("arrangementKeyInput"),
  arrangementKeyNativeBtn: document.getElementById("arrangementKeyNativeBtn"),
  arrangementKeyOffsetText: document.getElementById("arrangementKeyOffsetText"),
  applyAudioPreviewBtn: document.getElementById("applyAudioPreviewBtn"),
  resetAudioPreviewBtn: document.getElementById("resetAudioPreviewBtn"),
  audioPreviewText: document.getElementById("audioPreviewText"),
  tuningReferenceInput: document.getElementById("tuningReferenceInput"),
  tuningResetBtn: document.getElementById("tuningResetBtn"),
  tuningOffsetText: document.getElementById("tuningOffsetText"),
  tempoInput: document.getElementById("tempoInput"),
  timeInput: document.getElementById("timeInput"),
  analysisModeInput: document.getElementById("analysisModeInput"),
  analysisKeyInput: document.getElementById("analysisKeyInput"),
  minBpmInput: document.getElementById("minBpmInput"),
  maxBpmInput: document.getElementById("maxBpmInput"),
  beatOffsetInput: document.getElementById("beatOffsetInput"),
  onsetFrameInput: document.getElementById("onsetFrameInput"),
  onsetHopInput: document.getElementById("onsetHopInput"),
  chromaLowInput: document.getElementById("chromaLowInput"),
  chromaHighInput: document.getElementById("chromaHighInput"),
  alternativesInput: document.getElementById("alternativesInput"),
  chordSourceInput: document.getElementById("chordSourceInput"),
  demucsModelInput: document.getElementById("demucsModelInput"),
  useCacheInput: document.getElementById("useCacheInput"),
  simplifyChordsInput: document.getElementById("simplifyChordsInput"),
  lyricsEnabledInput: document.getElementById("lyricsEnabledInput"),
  lyricsSourceInput: document.getElementById("lyricsSourceInput"),
  lyricsModelInput: document.getElementById("lyricsModelInput"),
  lyricsLanguageInput: document.getElementById("lyricsLanguageInput"),
  chartRendererInput: document.getElementById("chartRendererInput"),
  lyricsReferencePanel: document.getElementById("lyricsReferencePanel"),
  chartPreview: document.getElementById("chartPreview"),
  chartReasonLabel: document.getElementById("chartReasonLabel"),
  chartReasonPane: document.getElementById("chartReasonPane"),
  barsTable: document.getElementById("barsTable"),
  barsBody: document.getElementById("barsBody"),
  addBarBtn: document.getElementById("addBarBtn"),
  duplicateBarBtn: document.getElementById("duplicateBarBtn"),
  splitBarBtn: document.getElementById("splitBarBtn"),
  mergeBarBtn: document.getElementById("mergeBarBtn"),
  deleteBarBtn: document.getElementById("deleteBarBtn"),
  reanalyzeChordsBtn: document.getElementById("reanalyzeChordsBtn"),
  reanalyzeLyricsBtn: document.getElementById("reanalyzeLyricsBtn"),
  reanalyzeAllBtn: document.getElementById("reanalyzeAllBtn"),
  clearLogBtn: document.getElementById("clearLogBtn"),
  analysisLog: document.getElementById("analysisLog"),
  timelineSummary: document.getElementById("timelineSummary"),
  timelineFollowInput: document.getElementById("timelineFollowInput"),
  timelineZoomInput: document.getElementById("timelineZoomInput"),
  zoomOutBtn: document.getElementById("zoomOutBtn"),
  zoomInBtn: document.getElementById("zoomInBtn"),
  zoomFitBtn: document.getElementById("zoomFitBtn"),
  timelineTransportInfo: document.getElementById("timelineTransportInfo"),
  timelinePlayState: document.getElementById("timelinePlayState"),
  timelineTimeText: document.getElementById("timelineTimeText"),
  timelineBarText: document.getElementById("timelineBarText"),
  timelineBeatText: document.getElementById("timelineBeatText"),
  timelineChordText: document.getElementById("timelineChordText"),
  timelineViewport: document.getElementById("timelineViewport"),
  playhead: document.getElementById("playhead"),
  chordLane: document.getElementById("chordLane"),
  lyricLane: document.getElementById("lyricLane"),
  beatLane: document.getElementById("beatLane"),
  visualStemLanes: document.getElementById("visualStemLanes"),
  arrangementResizeHandle: document.getElementById("arrangementResizeHandle"),
  detailBarLabel: document.getElementById("detailBarLabel"),
  detailSectionInput: document.getElementById("detailSectionInput"),
  detailChordInput: document.getElementById("detailChordInput"),
  detailStartInput: document.getElementById("detailStartInput"),
  detailRepeatStartInput: document.getElementById("detailRepeatStartInput"),
  detailRepeatEndInput: document.getElementById("detailRepeatEndInput"),
  detailLyricsInput: document.getElementById("detailLyricsInput"),
  detailNotesInput: document.getElementById("detailNotesInput"),
  detailLyricsReference: document.getElementById("detailLyricsReference"),
  detailAlternatives: document.getElementById("detailAlternatives"),
  chordSuggestion: document.getElementById("chordSuggestion"),
  globalProgressBar: document.getElementById("globalProgressBar"),
  topbarAnalysisBadge: document.getElementById("topbarAnalysisBadge"),
  topbarAnalysisText: document.getElementById("topbarAnalysisText"),
  navLogSpinner: document.getElementById("navLogSpinner"),
  logActiveBanner: document.getElementById("logActiveBanner"),
  logActiveText: document.getElementById("logActiveText"),
  loadingOverlay: document.getElementById("loadingOverlay"),
  loadingText: document.getElementById("loadingText"),
  collapseToggles: [...document.querySelectorAll(".collapse-toggle")],
  exportButtons: [...document.querySelectorAll("[data-export]")]
};
